version: "2"

services:
  server:
    image: bsferreira/mysql-fabric:1.0
    container_name: server
    networks:
      - my-net
    ports:
      - "3306:3306"
      - "32275:32275"
      - "32274:32274"
    environment:
      server: "10.0.2.15:3306"
      node1: "10.0.2.15:3307"
      node2: "10.0.2.15:3308"
      node3: "10.0.2.15:3309"
      NODE_SCRIPT: "server.sh"
      SERVER_ID: 0
      SERVER_PORT: 3306
  node1:
    image: bsferreira/mysql-fabric:1.0
    container_name: node1
    networks:
      - my-net
    ports:
      - "3307:3307"
    environment:
      server: "10.0.2.15:3306"
      node1: "10.0.2.15:3307"
      node2: "10.0.2.15:3308"
      node3: "10.0.2.15:3309"
      NODE_SCRIPT: "node.sh"
      SERVER_ID: 1
      SERVER_PORT: 3307
  node2:
    image: bsferreira/mysql-fabric:1.0
    container_name: node2
    networks:
      - my-net
    ports:
      - "3308:3308"
    environment:
      server: "ser10.0.2.15:3306"
      node1: "10.0.2.15:3307"
      node2: "10.0.2.15:3308"
      node3: "10.0.2.15:3309"
      NODE_SCRIPT: "node.sh"
      SERVER_ID: 2
      SERVER_PORT: 3308
  node3:
    image: bsferreira/mysql-fabric:1.0
    container_name: node3
    networks:
      - my-net
    ports:
      - "3309:3309"
    environment:
      server: "10.0.2.15:3306"
      node1: "10.0.2.15:3307"
      node2: "10.0.2.15:3308"
      node3: "10.0.2.15:3309"
      NODE_SCRIPT: "node.sh"
      SERVER_ID: 3
      SERVER_PORT: 3309
networks:
  my-net:
    driver: bridge
