version: "2"

services:
  server:
    image: bsferreira/mysql-fabric:1.0
    container_name: server
    networks:
      - my-net
    ports:
      - "$FABRIC_PORT:$FABRIC_PORT"
      - "32275:32275"
      - "32274:32274"
    environment:
      server: "$FABRIC_IP:$FABRIC_PORT"
      node1: "$NODE1_IP:$NODE1_PORT"
      node2: "$NODE2_IP:$NODE2_PORT"
      node3: "$NODE3_IP:$NODE3_PORT"
      NODE_SCRIPT: "server.sh"
      SERVER_ID: 0
      SERVER_PORT: $FABRIC_PORT
  node1:
    image: bsferreira/mysql-fabric:1.0
    container_name: node1
    networks:
      - my-net
    ports:
      - "$NODE1_PORT:$NODE1_PORT"
    environment:
      server: "$FABRIC_IP:$FABRIC_PORT"
      node1: "$NODE1_IP:$NODE1_PORT"
      node2: "$NODE2_IP:$NODE2_PORT"
      node3: "$NODE3_IP:$NODE3_PORT"
      NODE_SCRIPT: "node.sh"
      SERVER_ID: 1
      SERVER_PORT: $NODE1_PORT
  node2:
    image: bsferreira/mysql-fabric:1.0
    container_name: node2
    networks:
      - my-net
    ports:
      - "$NODE2_PORT:$NODE2_PORT"
    environment:
      server: "ser$HOST_IP:$FABRIC_PORT"
      node1: "$NODE1_IP:$NODE1_PORT"
      node2: "$NODE2_IP:$NODE2_PORT"
      node3: "$NODE3_IP:$NODE3_PORT"
      NODE_SCRIPT: "node.sh"
      SERVER_ID: 2
      SERVER_PORT: $NODE2_PORT
  node3:
    image: bsferreira/mysql-fabric:1.0
    container_name: node3
    networks:
      - my-net
    ports:
      - "$NODE3_PORT:$NODE3_PORT"
    environment:
      server: "$FABRIC_IP:$FABRIC_PORT"
      node1: "$NODE1_IP:$NODE1_PORT"
      node2: "$NODE2_IP:$NODE2_PORT"
      node3: "$NODE3_IP:$NODE3_PORT"
      NODE_SCRIPT: "node.sh"
      SERVER_ID: 3
      SERVER_PORT: $NODE3_PORT
networks:
  my-net:
    driver: bridge
